<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>1.0.0</version>
  <description>FYP Autonomous Vehicle System Bringup</description>
  <maintainer email="Kevinlasnh@outlook.com">kevinlasnh</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>livox_ros_driver2</exec_depend>
  <exec_depend>fastlio2</exec_depend>
  <exec_depend>pgo</exec_depend>
  <exec_depend>localizer</exec_depend>
  <exec_depend>interface</exec_depend>
  <exec_depend>nmea_navsat_driver</exec_depend>
  <exec_depend>um982_rtk_driver</exec_depend>
  <exec_depend>rtk_fgo_localizer</exec_depend>
  <exec_depend>gnss_calibration</exec_depend>
  <exec_depend>serial_twistctl</exec_depend>
  <exec_depend>serial_reader</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>nav2_mppi_controller</exec_depend>
  <exec_depend>nav2_rotation_shim_controller</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>waypoint_collector</exec_depend>
  <exec_depend>gps_waypoint_dispatcher</exec_depend>
  <exec_depend>indoor_navigation_manager</exec_depend>
  <exec_depend>spatio_temporal_voxel_layer</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
