imu_topic: /livox/imu
lidar_topic: /livox/lidar
# 机器人本体坐标系名称
# 已改动为 ROS2 标准名称 >> base_link
body_frame: base_link
# 里程计坐标系名称
# 已改动为 ROS2 标准名称 >> odom
world_frame: odom
print_time_cost: false

lidar_filter_num: 4
lidar_min_range: 0.5
lidar_max_range: 25.0
scan_resolution: 0.15
map_resolution: 0.3

cube_len: 300
det_range: 30
move_thresh: 1.5

na: 0.01
ng: 0.01
nba: 0.0001
nbg: 0.0001

imu_init_num: 20
near_search_num: 5
ieskf_max_iter: 5

gravity_align: true
esti_il: false

r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
t_il: [-0.011, -0.02329, 0.04412]

lidar_cov_inv: 1000.0

publish_cloud_height_filter_enabled: true
publish_cloud_min_z: -0.33
publish_cloud_max_z: 0.30
localization_cloud_enabled: true
localization_cloud_min_z: -0.20
localization_cloud_max_z: 1.80
nav2_obstacle_cloud_enabled: true
nav2_obstacle_cloud_min_z: -0.20
nav2_obstacle_cloud_max_z: 1.20
nav2_obstacle_self_filter_enabled: true
nav2_obstacle_self_filter_min_x: -0.40
nav2_obstacle_self_filter_max_x: 0.40
nav2_obstacle_self_filter_min_y: -0.30
nav2_obstacle_self_filter_max_y: 0.30
nav2_obstacle_self_patch_enabled: true
nav2_obstacle_self_patch_min_x: 0.40
nav2_obstacle_self_patch_max_x: 0.82
nav2_obstacle_self_patch_min_y: -0.35
nav2_obstacle_self_patch_max_y: -0.14
nav2_obstacle_self_patch_min_z: 0.25
nav2_obstacle_self_patch_max_z: 0.42
